import type { Metadata } from "next";
import "./../globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import Header from "@/components/ui/common/Header";
import Footer from "@/components/ui/common/Footer";
import MobileNav from "@/components/ui/common/MobileNav";

// const bigShoulder = BigShoulderDisplay({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Idighekere Udo - Projects",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main >
            <div
            className={`p-5 md:p-20`}
            >


                {/* <div className={`px-10 md:px-20`} >*/}
                {children}
                {/* </div> */}

            </div >
        </main >
    );
}
